
-- FanzCode - Mt --
--  --
-- ingin di recode? --
-- tag kami --
-- Base : AguzXzz --
-- Devloper Fnz : Adzy --
-- Plugin created : purrbits(senn) --
--  --
-- Btw sc ini ga suport Buton karena pakek bail original --
-- kalo mau suport button pakek lah Baileys mod kayak --
--  --
-- mengkodingan/baileys --
-- github:nstar-y/bail --
-- github:kiuur/bails // bisa pair costum --
-- npm:naruyaizumi // bisa costum pair juga --
-- dll cari aja sendiri ygy --
--  --
-- klo mau bail original tapi mau costum pair --
-- bisa pke bail @whiskeysockets/baileys: ^7.0.0-rc.2 --
--  --
--  --
-- terserah kamu aja si --
 