// ambil punya fiisya🗿
// https://github.com/Fiisya/simple-wabot 

global.galau = [
    "Gak salah kalo aku lebih berharap sama orang yang lebih pasti tanpa khianati janji-janji",
    "Rasanya baru kemarin kamu menawariku seblak. Lalu entah mengapa hari ini menanyakan kabar pun tidak.\n~vinaa",
    "What's the point of us being close yesterday?\n~Vinaa",
    "Kamu tidak bisa memaksa seseorang untuk menomor satukan dirimu, sebab prioritas dengan kebutuhan itu jelas beda.\n*BY PUTRI*",
    "Hubungan kita hanya sampai dilisan, tidak sampai dipertemukan.\n*BY PUTRI*",
    "Dia sesuka hati, kamu setulus hati.\n*BY PUTRI*",
    "Mengakhiri bukan berarti tidak mau berjuang lagi...hanya saja aku tidak mau ada lgi,hati yg tersakiti.\n\nBy putri",
    "Maaf. Tidak ada waktu untuk meladeni gabutmu. Karena aku sibuk dengan kesibukan ku.\n*BY PUTRI*",
    "Pelangimu mungkin banyak warna. Tapi, tak ada warna yang membuat dia menaruh rasa.\n*BY PUTRI*",
    "Bahagia terus ya,sampai saat ini lu masih jadi tokoh favorit dikisah hidup gue,luv u.\n\n*BY PUTRI*",
    "Sorry,gue ga kuat buat semuanya ,mksi ya\n\n*BY PUTRI*",
    "Kamu memang sosok yg tak terduga Mudah membuat ku bahagia,mudah membuatku hancur saat itu juga.\n\n*BY PUTRI*",
    "Harusnya kalo udah ga sayang sama aku tu bilang aja gausa di tutup tutupin\n*BY INDI*",
    "Kalau aku memang tidak sayang sama kamu ngapain aku mikirin kamu. Tapi semuanya kamu yang ngganggap aku gak sayang sama kamu",
    "Jangan iri dan sedih jika kamu tidak memiliki kemampuan seperti yang orang miliki. Yakinlah orang lain juga tidak memiliki kemampuan sepertimu",
    "Hanya kamu yang bisa membuat langkahku terhenti, sambil berkata dalam hati mana bisa aku meninggalkanmu",
    "Tetap tersenyum walaluku masih dibuat menunggu dan rindu olehmu, tapi itu demi kamu",
    "Tak semudah itu melupakanmu",
    "Secuek-cueknya kamu ke aku, aku tetap sayang sama kamu karena kamu telah menerima aku apa adanya",
    "Aku sangat bahagia jika kamu bahagia didekatku, bukan didekatnya",
    "Jadilah diri sendiri, jangan mengikuti orang lain, tetapi tidak sanggup untuk menjalaninya",
    "Cobalah terdiam sejenak untuk memikirkan bagaimana caranya agar kita dapat menyelesaikan masalah ini bersama-sama",
    "Bisakah kita tidak bermusuhan setelah berpisah, aku mau kita seperti dulu sebelum kita jadian yang seru-seruan bareng, bercanda dan yang lainnya",
    "Aku ingin kamu bisa langgeng sama aku dan yang aku harapkan kamu bisa jadi jodohku",
    "Cinta tak bisa dijelaskan dengan kata-kata saja, karena cinta hanya mampu dirasakan oleh hati",
    "Masalah terbesar dalam diri seseorang adalah tak sanggup melawan rasa takutnya",
    "Selamat pagi buat orang yang aku sayang dan orang yang membenciku, semoga hari ini hari yang lebih baik daripada hari kemarin buat aku dan kamu",
    "Jangan menyerah dengan keadaanmu sekarang, optimis karena optimislah yang bikin kita kuat",
    "Kepada pria yang selalu ada di doaku aku mencintaimu dengan tulus apa adanya",
    "Tolong jangan pergi saat aku sudah sangat sayang padamu",
    "Coba kamu yang berada diposisiku, lalu kamu ditinggalin gitu aja sama orang yang lo sayang banget",
    "Aku takut kamu kenapa-napa, aku panik jika kamu sakit, itu karena aku cinta dan sayang padamu",
    "Sakit itu ketika cinta yang aku beri tidak kamu hargai",
    "Kamu tiba-tiba berubah tanpa sebab tapi jika memang ada sebabnya kamu berubah tolong katakan biar saya perbaiki kesalahan itu",
    "Karenamu aku jadi tau cinta yang sesungguhnya",
    "Senyum manismu sangatlah indah, jadi janganlah sampai kamu bersedih",
    "Berawal dari kenalan, bercanda bareng, ejek-ejekan kemudian berubah menjadi suka, nyaman dan akhirnya saling sayang dan mencintai",
    "Tersenyumlah pada orang yang telah menyakitimu agar sia tau arti kesabaran yang luar biasa",
    "Aku akan ingat kenangan pahit itu dan aku akan jadikan pelajaran untuk masa depan yang manis",
    "Kalau memang tak sanggup menepati janjimu itu setidaknya kamu ingat dan usahakan jagan membiarkan janjimu itu sampai kau lupa",
    "Hanya bisa diam dan berfikir Kenapa orang yang setia dan baik ditinggalin yang nakal dikejar-kejar giliran ditinggalin bilangnya laki-laki itu semuanya sama",
    "Walaupun hanya sesaat saja kau membahagiakanku tapi rasa bahagia yang dia tidak cepat dilupakan",
    "Aku tak menyangka kamu pergi dan melupakan ku begitu cepat",
    "Jomblo gak usah diam rumah mumpung malam minggu ya keluar jalan lah kan jomblo bebas bisa dekat sama siapapun pacar orang mantan sahabat bahkan sendiri atau bareng setan pun bisa",
    "Kamu adalah teman yang selalu di sampingku dalam keadaan senang maupun susah Terimakasih kamu selalu ada di sampingku",
    "Aku tak tahu sebenarnya di dalam hatimu itu ada aku atau dia",
    "Tak mudah melupakanmu karena aku sangat mencintaimu meskipun engkau telah menyakiti aku berkali-kali",
    "Hidup ini hanya sebentar jadi lepaskan saja mereka yang menyakitimu Sayangi Mereka yang peduli padamu dan perjuangan mereka yang berarti bagimu",
    "Tolong jangan pergi meninggalkanku aku masih sangat mencintai dan menyayangimu",
    "Saya mencintaimu dan menyayangimu jadi tolong jangan engkau pergi dan meninggalkan ku sendiri",
    "Saya sudah cukup tahu bagaimana sifatmu itu kamu hanya dapat memberikan harapan palsu kepadaku",
    "Aku berusaha mendapatkan cinta darimu tetapi Kamunya nggak peka",
    "Aku bangkit dari jatuh ku setelah kau jatuhkan aku dan aku akan memulainya lagi dari awal Tanpamu",
    "Mungkin sekarang jodohku masih jauh dan belum bisa aku dapat tapi aku yakin jodoh itu Takkan kemana-mana dan akan ku dapatkan",
    "Datang aja dulu baru menghina orang lain kalau memang dirimu dan lebih baik dari yang kau hina",
    "Membelakanginya mungkin lebih baik daripada melihatnya selingkuh didepan mata sendiri",
    "Bisakah hatimu seperti angsa yang hanya setia pada satu orang saja",
    "Aku berdiri disini sendiri menunggu kehadiran dirimu",
    "Aku hanya tersenyum padamu setelah kau menyakitiku agar kamu tahu arti kesabaran",
    "Maaf aku lupa ternyata aku bukan siapa-siapa",
    "Untuk memegang janjimu itu harus ada buktinya jangan sampai hanya janji palsu",
    "Aku tidak bisa selamanya menunggu dan kini aku menjadi ragu Apakah kamu masih mencintaiku",
    "Jangan buat aku terlalu berharap jika kamu tidak menginginkanku",
    "Lebih baik sendiri daripada berdua tapi tanpa kepastian",
    "Pergi bukan berarti berhenti mencintai tapi kecewa dan lelah karena harus berjuang sendiri",
    "Bukannya aku tidak ingin menjadi pacarmu Aku hanya ingin dipersatukan dengan cara yang benar",
    "Akan ada saatnya kok aku akan benar-benar lupa dan tidak memikirkan mu lagi",
    "Kenapa harus jatuh cinta kepada orang yang tak bisa dimiliki",
    "Jujur aku juga memiliki perasaan terhadapmu dan tidak bisa menolakmu tapi aku juga takut untuk mencintaimu",
    "Maafkan aku sayang tidak bisa menjadi seperti yang kamu mau",
    "Jangan memberi perhatian lebih seperti itu cukup biasa saja tanpa perlu menimbulkan rasa",
    "Aku bukan mencari yang sempurna tapi yang terbaik untukku",
    "Sendiri itu tenang tidak ada pertengkaran kebohongan dan banyak aturan",
    "Cewek strong itu adalah yang sabar dan tetap tersenyum meskipun dalam keadaan terluka",
    "Terima kasih karena kamu aku menjadi lupa tentang masa laluku",
    "Cerita cinta indah tanpa masalah itu hanya di dunia dongeng saja",
    "Kamu tidak akan menemukan apa-apa di masa lalu Yang ada hanyalah penyesalan dan sakit hati",
    "Mikirin orang yang gak pernah mikirin kita itu emang bikin gila",
    "Dari sekian lama menunggu apa yang sudah didapat",
    "Perasaan Bodo gue adalah bisa jatuh cinta sama orang yang sama meski udah disakiti berkali-kali",
    "Yang sendiri adalah yang bersabar menunggu pasangan sejatinya",
    "Aku terlahir sederhana dan ditinggal sudah biasa",
    "Aku sayang kamu tapi aku masih takut untuk mencintaimu",
    "Bisa berbagi suka dan duka bersamamu itu sudah membuatku bahagia",
    "Aku tidak pernah berpikir kamu akan menjadi yang sementara",
    "Jodoh itu bukan seberapa dekat kamu dengannya tapi seberapa yakin kamu dengan Allah",
    "Jangan paksa aku menjadi cewek seperti seleramu",
    "Hanya yang sabar yang mampu melewati semua kekecewaan",
    "Balikan sama kamu itu sama saja bunuh diri dan melukai perasaan ku sendiri",
    "Tak perlu membalas dengan menyakiti biar Karma yang akan urus semua itu",
    "Aku masih ingat kamu tapi perasaanku sudah tidak sakit seperti dulu",
    "Punya kalimat sendiri & mau ditambahin? chat *.owner*",
];

global.senja = [
    "Senja selalu cantik kecuali saat kau patah hati.",
    "Aku masih rindu. Namun senja tak ingin lama bertamu.",
    "Ada yang tak tenggelam ketika senja datang, yakni rasa.",
    "Karena senja selalu menerima langit apa adanya.",
    "Setiap senja selalu menjanjikan kita awal yang baru.",
    "Senja telah mengajarkanku apa arti dari mengikhlaskan.",
    "Biar lelah, tapi dia tetap indah. Itulah senja.",
    "Senja tak pernah salah, hanya kenangan yang membuatnya basah.",
    "Hanya senja yang tau cara berpamitan dengan indah.",
    "Senja, perpaduan yang sungguh indah bagi alam semesta.",
    "Selepas senja, aku kembali menjadi manusia yang menutupi air mata dengan gelak tawa.",
    "Senjaku mulai menepi ke peraduannya.",
    "Karena senja tak pernah memintamu menunggu.",
    "Entah mana yang lebih indah, senja yang mulai memerah atau senyummu yang mulai merekah.",
    "Senja tak pernah membenci awan kelabu yang sering menutupinya.",
    "Jadilah seperti senja yang kehadirannya selalu membuat ketenangan dan kepergiannya selalu membuat kerinduan.",
    "Kamu seperti senja,terasa menyenangkan namun tak bertahan lama.",
    "Aku hanya dapat menikmati kehangatan senja yang tak akan pernah untuk menikmati kehangatan pelukanmu.",
    "Senja telah mengajarkan ku apa arti dari mengikhlaskan.",
    "Kamu bagaikan senja di sore hari, indah sesaat kemudian menghilang.",
    "Senja mengajarkan kita bahwa keindahan tak harus datang lebih awal.",
    "Senja tak pernah salah, hanya kenangan yang membuatnya basah.",
    "Kenyataanya senja tetaplah senja. Dia tak punya rasa, dia memberi indah sesaat kepada penikmatnya, lalu pergi begitu saja.",
    "Di antara senja dan keheningan tempat ini, mengingatmu menjadi kesibukan kecil yang membahagiakan.",
    "Di ujung senja yang sudah hampir hilang kali ini aku masih menanti sebuah kabar dan ku tak tahu harus berapa lama ku menunggu.",
    "Untuk luka yang terhapus senja, untuk duka yang makin meraja, yakinlah hati agar membaja, bisikan lembut dengan senyuman manja, Insyaallah bersama Allah semuanya akan baik-baik saja.",
    "Saat senja menyapa, aku menyadari bahwa masih banyak hal indah yang Tuhan ciptakan selain Kamu.",
    "Demi matahari senja yang menggantung manis manja di cakrawala, demi kebaikan dan ketulusan yang telaten diberikan semesta, dan demi ragam nama-nama Tuhan baik yang akrab maupun asing di telinga kita, sesungguhnya, manusia, adalah mahkluk yang merugi. Kecuali, ia yang mau belajar pada masa silam, berbuat yang terbaik di masa sekarang, dan menyiapkan segala sesuatu di masa depan, dengan keyakinan paling yakin pada terwujudnya sebuah impian.",
    "Tuhan, bersama tenggelamnya matahari senja ini, redakanlah kekecewaan dan kemarahan di hati ini. Sabarkanlah aku. Aamiin.",
    "Nikmat Allah mana yang kau dustakan disenja ini wahai saudara-saudaraku semua.",
    "Di tengah angin senja yang mendesak, aku merasakan kekuasaan waktu, yang tanpa pandang bulu mengubah segala-galanya.",
    "Terkadang senja mengingatkan pada rumah, pada orang-orang yang membuat hati kita rindu untuk pulang.",
    "Salah satu nikmat Allah yang sampai detik ini bisa kurasakan adalah masih bisa bernapas dan menghirup segarnya udara senja.",
    "Salam senja dan Magrib. Doa kita kepada yang maha kuasa hanya taubat jawabannya, dosa kita kepada sesama berminta maaf penawarnya.",
    "Gelombang adzan mendayu meminang senja. Di sanalah, Tuhan melahirkan segala rindu.",
    "Engkau terkadang datang seperti jingga di kala senja, datang dengan keindahan berlalu menyisakan kegelapan.",
    "Senja: Mengajarkan kita bahwa yang indah pasti akan tenggelam.",
    "Senja pergi secara perlahan, karena ia tahu pergi secara tiba-tiba hanya menyakiti siapapun yang menikmatinya.",
    "Walau senja tinggalkan keindahan dan pergi, ia selalu datang kembali di esok hari. Tak seperti kamu yang lebih indah dari senja tapi pergi entah kemana.",
    "Ku mencintai kau seperti senja. Dengan keindahannya, tanpa durasinya.",
    "Jangan mengulangi kesalahan yang sama, karena masih banyak kesalahan kesalahan lain yang perlu dicoba.",
    "Terima kasih senja, kau telah menampakkan bahwa perpisahan tak semuanya menyakitkan. Dan kepergian tampak begitu indah tanpa kehangatan.",
    "Senja itu seperti kita, singkat dan bahagia.",
    "Aku hanyalah penikmat kehangatan senja yang tak akan bisa menikmati kehangatan pelukanmu.",
    "Hari ini aku belajar dari senja bahwa yang indah dan mempesona akan hilang dan tenggelam pada waktunya.",
    "Tanaman palsuku mati karena aku tidak berpura pura menyiramnya.",
    "Jangan rindu berat, kamu nggak akan kuat. Biar aku saja yang merindukanmu sekalipun bertambah berat badanku.",
    "Bermimpilah setinggi langit, jika kamu terjatuh berarti tidurmu kurang ke tengah.",
    "Dusk is proof that no matter what happens, everyday can end beautifully.",
    "From the twilight I learned that every beautiful things had to go through all the painful things.",
    "Twilight drops her curtain down, and pins it with a star. Lucky Maud Montgomery.",
    "Dusk teaches us that life is not always bright and shining.",
    "Twilight comes in a beautiful way. As beautiful as God ways in meet us.",
    "Every sunset bring a promise for a new dawn. -Ralph Waldo Emerson",
    "Dusk teaches us to appreciate all the great things the sun gives us.",
    "Don't forget that beautiful twilight needs blackened clouds.",
    "And dusk makes us understand the meaning of the word 'willing'.",
    "Twilight fell: The sky turned to a light, dusky purple littered with tiny silver stars. J.K. Rowling",
    "Pengagum senja, penyesap kopi, penikmat rindu, penimba ilmu, peninggi badan, pemanjat sutet, pembuka simontok, penyembah tutup botol.",
    "Tangannya menjadi pengganti tanganku untuk menuntunmu' Pundaknya menjadi pengganti pundakku untukmu bersandar. Biarlah gemercik gerimis, carik senja, secangkir teh, dan bait lagu menjadi penggantimu.",
    "Mulai mempertanyakan alam raya, galaksi, planet-planet dan eksistensi saya di muka bumi ketika pagi-pagi belum juga ingin buang air besar.",
    "Jodoh tak akan ke mana-mana terlebih dahulu sebelum akhirnya menetap.",
    "Jatuh hati tidak pernah bisa memilih. Tuhan memilihkan. Kita hanyalah korban. Kecewa adalah konsekuensi, bahagia adalah bonus.",
    "Hujan dan gebetan itu mirip. Ada yang mengaku suka, tapi hanya memandangnya dari tempat duduk yang hangat, berkata-kata romantis tanpa pernah mau bersinggungan. Ada yang betulan suka, mengalahkan rasa tidak nyaman, langsung berinteraksi dengannya meski berisiko sakit.",
    "Enak atau tidaknya ucapan selamat malam dan selamat pagi itu tergantung siapa yang mengucapkan.",
    "Denganmu, basa-basi terasa berisi.",
    "Absurd sekali, kita. Cerita berjam-jam, lalu hilang kabar berhari-hari. Merindu diam-diam, hingga tidak lagi saling mencari.",
    "Aku lelah sembunyi, lelah merindukanmu dalam sunyi. Tanganku jangan dijabat, baiknya digenggam saja. Tak cuma jadi sahabat, jadi kekasihmu juga.",
    "Jangan pernah lupa, bahwa awan menghitam adalah yang membuat senja terlihat sempurna.",
    "Meski senja tiba di ujung mata, rindu enggan tinggalkan kita, tak peduli dengan siapa menanti malam, rindu ini senantiasa menyapa.",
    "Ketika senja mulai tenggelam, ku mulai menyadari kamu yang paling berarti, dan ketika sinar matahari menyapa ku sadari kamu hanya mimpi.",
    "Senjaku berlari mengejar ketinggalannya, menyusuri setapak di tepian jurang menganga, di bawahnya riuh ombak berirama lara.",
    "Jika kamu senja, maka aku jingga. Muncul bersama, hilang pun juga.",
    "Matahari yang tenggelam akan mengajarkan pada kita, agar bisa menghargai apa yang diberikan matahari untuk kita.",
    "Senja begitu cepat berganti, dan sampai saat ini kau tetap kunanti.",
    "Senja memang begitu indah, namun cahaya mentari tetap tak tergantikan, meski dengan lilin yang bersinar sangat terang sekalipun.",
    "Saat jingga bersetubuh dengan gelap, sepasang mata sibuk kemasi air matanya; seakan takut, senja mencuri rindu miliknya.",
    "Senja mengajarkan pada kita, bahwa kehidupan tak selalu berjalan dengan cemerlang dan bersinar.",
];

global.renungan = [
    "https://telegra.ph/file/f52f8d6312f3ac2590727.jpg",
    "https://telegra.ph/file/35cb9decc525a3453ba87.jpg",
    "https://telegra.ph/file/5996566cb5cd615f60f51.jpg",
    "https://telegra.ph/file/87ecb0f385ae390c609e8.jpg",
    "https://telegra.ph/file/7ca48dd2329937b7f86da.jpg",
    "https://telegra.ph/file/e2d603fa0ec9004ca9e2f.jpg",
    "https://telegra.ph/file/f8f9ac3d38c9e3c9456ec.jpg",
    "https://telegra.ph/file/9e1f626f4005b6f16d904.jpg",
    "https://telegra.ph/file/6300478b6ffdf0c0001e9.jpg",
    "https://telegra.ph/file/dca222749fb98ce0384f7.jpg",
    "https://telegra.ph/file/295f6f6164794a2156d2e.jpg",
    "https://telegra.ph/file/429cb39112f2870327398.jpg",
    "https://telegra.ph/file/9d96d5fcc89c6f30e086f.jpg",
    "https://telegra.ph/file/c396c9da3800536792139.jpg",
    "https://telegra.ph/file/6d2fc9ac5c878fa93c43f.jpg",
    "https://telegra.ph/file/09174bfbe94a756a90411.jpg",
    "https://telegra.ph/file/2dcd363e5f9eb42d88cc0.jpg",
    "https://telegra.ph/file/798daf4f7a87bbabc8694.jpg",
    "https://telegra.ph/file/4052c388390385d9c79f3.jpg",
    "https://telegra.ph/file/d8f1a14f712d6a860b36c.jpg",
    "https://telegra.ph/file/eed16ec2df3cc22102e7b.jpg",
    "https://telegra.ph/file/0738833300f1620285b36.jpg",
    "https://telegra.ph/file/dc464f93b5a579c279979.jpg",
    "https://telegra.ph/file/0e0aa4e97675b2e649ddc.jpg",
    "https://telegra.ph/file/2b58e9e63b38ac837e8cd.jpg",
    "https://telegra.ph/file/49029a0e94ee5d710b6a9.jpg",
    "https://telegra.ph/file/3a1ecc7774208670ec781.jpg",
    "https://telegra.ph/file/46a125a6a3dc13cee931e.jpg",
    "https://telegra.ph/file/37c358438489180b48723.jpg",
    "https://telegra.ph/file/6287bc3f9b7876aeb5554.jpg",
    "https://telegra.ph/file/684f268210c2de5d44bc6.jpg",
    "https://telegra.ph/file/166b0d7fd1fcc55a09449.jpg",
    "https://telegra.ph/file/f6713bdd595530bb38df9.jpg",
    "https://telegra.ph/file/6738bff78091aa85a6cd7.jpg",
    "https://telegra.ph/file/370d394c23fd162c6c9be.jpg",
    "https://telegra.ph/file/38f2ceb0daf966fe7ddcf.jpg",
    "https://telegra.ph/file/d23c4cedab7bf64915ba2.jpg",
    "https://telegra.ph/file/3e72698c996538ee50ccf.jpg",
    "https://telegra.ph/file/0379370add3bbae122008.jpg",
    "https://telegra.ph/file/873d1b18acf16088786ca.jpg",
    "https://telegra.ph/file/823e0664c7edec135b847.jpg",
    "https://telegra.ph/file/8c8da910ab52c7a2b7ccf.jpg",
    "https://telegra.ph/file/8037b52b84e8c39060f89.jpg",
    "https://telegra.ph/file/e6da062c873aca03d25d4.jpg",
    "https://telegra.ph/file/ef307b95c45e77defd0e1.jpg",
    "https://telegra.ph/file/d66123bde1e967adf72b9.jpg",
    "https://telegra.ph/file/7a2a376d1d152d382ae1a.jpg",
    "https://telegra.ph/file/f8d0253bb97ea30e04275.jpg",
    "https://telegra.ph/file/bbe65705f8dc9558eb177.jpg",
    "https://telegra.ph/file/c7530031da08b4441ee9f.jpg",
    "https://telegra.ph/file/5c1f7320f1b457911c3c2.jpg",
    "https://telegra.ph/file/5a8600f4651e9497f6562.jpg",
    "https://telegra.ph/file/053032e59ced4dac9ed3d.jpg",
    "https://telegra.ph/file/ef61d077b685d47a11ff0.jpg",
    "https://telegra.ph/file/c8a5cc9b9da57299a1f25.jpg",
    "https://telegra.ph/file/2ed057545501fc3bc8de0.jpg",
    "https://telegra.ph/file/b3b7c0c22e7dba04cab03.jpg",
    "https://telegra.ph/file/62579a62376550e6590b1.jpg",
    "https://telegra.ph/file/d140b0791799af2f67315.jpg",
    "https://telegra.ph/file/81fd213f74b1235ef18fc.jpg",
    "https://telegra.ph/file/d00db1507843f4ead46d8.jpg",
    "https://telegra.ph/file/dedfa2294f4eb845acac4.jpg",
    "https://telegra.ph/file/2b3700178b39c9c01e9b4.jpg",
    "https://telegra.ph/file/a7be3d06c7dd9b8475579.jpg",
    "https://telegra.ph/file/f7d91295ec35c44af8c90.jpg",
    "https://telegra.ph/file/01e42d9181311dd7d2d70.jpg",
    "https://telegra.ph/file/e5cf6db288acbfbb13f2b.jpg",
    "https://telegra.ph/file/5a6ee797141b96fcebcce.jpg",
    "https://telegra.ph/file/88d5b22d7a40365f59fc4.jpg",
    "https://telegra.ph/file/0de4de20e35f6c9b12af6.jpg",
    "https://telegra.ph/file/6b60a05a32e7bdbb62c2d.jpg",
    "https://telegra.ph/file/549e5a1dbd0aebbd909c6.jpg",
    "https://telegra.ph/file/d9d0c658ef1ea088d3579.jpg",
    "https://telegra.ph/file/4c8fa9809897b7bd3eb03.jpg",
    "https://telegra.ph/file/a58ee2c51fdc6c78ed7f6.jpg",
    "https://telegra.ph/file/f2253a885cb84af5d588c.jpg",
    "https://telegra.ph/file/f17bd255b176da6943240.jpg",
    "https://telegra.ph/file/279afb02b1fcf93abdae4.jpg",
    "https://telegra.ph/file/8ba4a8f31cf0673f6aa87.jpg",
    "https://telegra.ph/file/c842818563065460b022e.jpg",
    "https://telegra.ph/file/99e10142aeef70961437a.jpg",
    "https://telegra.ph/file/33da8321603f78cd165f4.jpg",
    "https://telegra.ph/file/63678732998176b22fa96.jpg",
    "https://telegra.ph/file/b79bb874be90a34cd5786.jpg",
    "https://telegra.ph/file/148875b883f91ac8b42e6.jpg",
    "https://telegra.ph/file/275d948e0ed99652b4c52.jpg",
    "https://telegra.ph/file/dbfa4e1043d1bbc9441b2.jpg",
    "https://telegra.ph/file/1ab030093aea5937e0468.jpg",
    "https://telegra.ph/file/b5b64e5e5ee0df73bc5b5.jpg",
    "https://telegra.ph/file/a7032cdd783d8f1656424.jpg",
    "https://telegra.ph/file/5ea4218fedab8e124496b.jpg",
    "https://telegra.ph/file/0e0fef10d278f886a5f4a.jpg",
    "https://telegra.ph/file/09e81d73081d6f2811ca3.jpg",
    "https://telegra.ph/file/816866bef7a307029e6b6.jpg",
    "https://telegra.ph/file/5b5736027ae57a787d00c.jpg",
    "https://telegra.ph/file/68899ab649fa4711905ce.jpg",
    "https://telegra.ph/file/47b0c825cdf8ebaa90a05.jpg",
    "https://telegra.ph/file/06aaa229521191de3895e.jpg",
    "https://telegra.ph/file/68551e562c4e343efd965.jpg",
    "https://telegra.ph/file/9487c11c728cd279b8da3.jpg"
]